/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import practica3.Matrizcontroller;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSE SALAZAR
 */
public class Frmejercisio2 extends javax.swing.JDialog {
   private  Matrizcontroller mz = new Matrizcontroller();
    /**
     * Creates new form Frmejercisio2
     */
    public Frmejercisio2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfilas = new javax.swing.JTextField();
        txtcolumnas = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MATRICES NUMEROS");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 3, 14)); // NOI18N
        jLabel1.setText("MATRIZ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 50, 20);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dimension"));
        jPanel2.setLayout(null);

        jLabel2.setText("Filas:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 40, 15);

        jLabel3.setText("Columnas:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 70, 70, 15);

        txtfilas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfilasActionPerformed(evt);
            }
        });
        jPanel2.add(txtfilas);
        txtfilas.setBounds(80, 20, 40, 30);

        txtcolumnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcolumnasActionPerformed(evt);
            }
        });
        jPanel2.add(txtcolumnas);
        txtcolumnas.setBounds(80, 60, 40, 30);

        jButton1.setText("Generar matriz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(150, 40, 110, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 30, 330, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 140);

        setSize(new java.awt.Dimension(369, 183));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcolumnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcolumnasActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtcolumnasActionPerformed

    private void txtfilasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfilasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfilasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
        if (txtfilas.getText().isEmpty() || txtcolumnas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene todo los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int filas = Integer.parseInt(txtfilas.getText().trim());
        int columnas = Integer.parseInt(txtcolumnas.getText().trim());

        if (filas <= 0 || columnas <= 0) {
            JOptionPane.showMessageDialog(this, "Ingrese valores mayores a cero", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

             
             int[][] matriz = mz.matrizNumeros(filas, columnas);
             FrmMatriz frmMatriz = new FrmMatriz(this, true, matriz); 
             frmMatriz.setVisible(true);;


    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingrese números válidos", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmejercisio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmejercisio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmejercisio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmejercisio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frmejercisio2 dialog = new Frmejercisio2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcolumnas;
    private javax.swing.JTextField txtfilas;
    // End of variables declaration//GEN-END:variables
}
