/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;
import practica3.Laberintocontroller;
/**
 *
 * @author JOSE SALAZAR
 */
public class Frmlaberintolong extends javax.swing.JDialog {
private Laberintocontroller controller = new Laberintocontroller();
    /**
     * Creates new form Frmlaberintolong
     */
    public Frmlaberintolong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtaltura = new javax.swing.JTextField();
        txtancho = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opcion de laberinto");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Laberinto");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 80, 15);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Opciones del laberinto"));
        jPanel2.setLayout(null);

        jLabel2.setText("Altura:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 70, 15);

        jLabel3.setText("Ancho:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 60, 60, 15);

        txtaltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalturaActionPerformed(evt);
            }
        });
        jPanel2.add(txtaltura);
        txtaltura.setBounds(90, 20, 80, 30);

        txtancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanchoActionPerformed(evt);
            }
        });
        jPanel2.add(txtancho);
        txtancho.setBounds(90, 60, 80, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 40, 250, 100);

        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(90, 150, 90, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 200);

        setSize(new java.awt.Dimension(284, 223));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtanchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanchoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        int alto = Integer.parseInt(txtaltura.getText());
        int ancho = Integer.parseInt(txtancho.getText());

        if (alto != ancho) {
            javax.swing.JOptionPane.showMessageDialog(this, "Solo se permiten laberintos cuadrados");
            return;
        }

        String[][] laberinto = controller.generarLaberinto(alto);

        // Mostrar en tabla
        FrmLaberinto ventanaLaberinto = new FrmLaberinto(new javax.swing.JFrame(), true);
        ventanaLaberinto.mostrarLaberinto(laberinto);
        ventanaLaberinto.setVisible(true);

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debes ingresar números válidos.");
    } catch (IllegalArgumentException e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtalturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmlaberintolong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmlaberintolong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmlaberintolong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmlaberintolong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frmlaberintolong dialog = new Frmlaberintolong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtancho;
    // End of variables declaration//GEN-END:variables
}
