/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

/**
 *
 * @author JOSE SALAZAR
 */
public class FrmLaberinto extends javax.swing.JDialog {

    /**
     * Creates new form FrmLaberinto
     */
    public FrmLaberinto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Laberinto");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(63, 49, 100, 100);

        jPanel2.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 470, 300);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 470, 300);

        setSize(new java.awt.Dimension(484, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public void mostrarLaberinto(String[][] laberinto) {
    int dimension = laberinto.length;

    // Crear nombres de columnas (1,2,3,...)
    String[] columnas = new String[dimension];
    for (int i = 0; i < dimension; i++) {
        columnas[i] = String.valueOf(i + 1);
    }

    // Crear datos para la tabla (Object[][])
    Object[][] datos = new Object[dimension][dimension];
    for (int i = 0; i < dimension; i++) {
        for (int j = 0; j < dimension; j++) {
            datos[i][j] = laberinto[i][j];
        }
    }

    // Crear modelo y asignarlo
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(datos, columnas) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // No editable
        }
    };

    jTable1.setModel(modelo);

    // Ajustar tamaño tabla y panel según dimensión
    int cellSize = 30; // tamaño de celda en pixeles, puedes cambiar
    int tablaWidth = dimension * cellSize;
    int tablaHeight = dimension * cellSize;

    jTable1.setRowHeight(cellSize);

    jTable1.setPreferredScrollableViewportSize(new java.awt.Dimension(tablaWidth, tablaHeight));
    jTable1.setFillsViewportHeight(true);

    jScrollPane1.setBounds(0, 0, tablaWidth + 20, tablaHeight + 20);
    jPanel2.setBounds(0, 0, tablaWidth + 20, tablaHeight + 20);

    // Ajustar tamaño del diálogo
    this.setSize(tablaWidth + 50, tablaHeight + 80);

    // Reubicar componentes si hace falta (opcional)
    this.setLocationRelativeTo(null);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLaberinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmLaberinto dialog = new FrmLaberinto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
