/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import practica3.Casacontroller;

/**
 *
 * @author JOSE SALAZAR
 */
public class FrmregistroCasa extends javax.swing.JDialog {
private Casacontroller cs = new Casacontroller();
    /**
     * Creates new form FrmregistroCasa
     */
    public FrmregistroCasa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
     
    }
    private void cargarTabla() {
    String[][] datos = cs.listar();

    if (datos != null) {
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); // limpiar tabla

        for (int i = 0; i < datos.length; i++) {
            String barrio = datos[i][1];
            int pisos = Integer.parseInt(datos[i][4]);
            float largo = Float.parseFloat(datos[i][2]);
            float ancho = Float.parseFloat(datos[i][3]);

            String homonima = cs.esHomonima(i,pisos, largo, ancho) ? "Homonima" : "";

            Object[] fila = { barrio, pisos, largo, ancho, homonima };
            modelo.addRow(fila);
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbarrio = new javax.swing.JTextField();
        txtpisos = new javax.swing.JTextField();
        txtlargo = new javax.swing.JTextField();
        txtancho = new javax.swing.JTextField();
        buttonregistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrocasa");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Registro Casa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 80, 30);

        jLabel2.setText("Barrio:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 50, 50, 15);

        jLabel3.setText("Largo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 120, 60, 20);

        jLabel4.setText("Ancho:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 80, 50, 20);

        jLabel5.setText("Numero de pisos:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 90, 120, 15);

        txtbarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarrioActionPerformed(evt);
            }
        });
        jPanel1.add(txtbarrio);
        txtbarrio.setBounds(130, 40, 130, 30);

        txtpisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpisosActionPerformed(evt);
            }
        });
        jPanel1.add(txtpisos);
        txtpisos.setBounds(130, 80, 40, 30);

        txtlargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlargoActionPerformed(evt);
            }
        });
        jPanel1.add(txtlargo);
        txtlargo.setBounds(130, 120, 40, 30);

        txtancho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtanchoActionPerformed(evt);
            }
        });
        jPanel1.add(txtancho);
        txtancho.setBounds(280, 80, 40, 30);

        buttonregistrar.setText("Registrar");
        buttonregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonregistrarActionPerformed(evt);
            }
        });
        jPanel1.add(buttonregistrar);
        buttonregistrar.setBounds(220, 120, 80, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Barrio", "Pisos", "Largo", "Ancho", "Homonimas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 380, 270);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 520);

        setSize(new java.awt.Dimension(416, 563));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtbarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarrioActionPerformed

    private void txtpisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpisosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpisosActionPerformed

    private void txtlargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlargoActionPerformed

    private void txtanchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtanchoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtanchoActionPerformed

    private void buttonregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonregistrarActionPerformed
        // TODO add your handling code here:
    try {
        String barrio = txtbarrio.getText();
        int pisos = Integer.parseInt(txtpisos.getText());
        float largo = Float.parseFloat(txtlargo.getText());
        float ancho = Float.parseFloat(txtancho.getText());

        // Generar número automático
        int nrocasa = Integer.parseInt(cs.numerarCasas());

        boolean registrado = cs.registroCasa(nrocasa, barrio, largo, ancho, pisos);

        if (registrado) {
            cargarTabla(); // Actualizar tabla
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Datos inválidos: " + e.getMessage());
    }
    }//GEN-LAST:event_buttonregistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmregistroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmregistroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmregistroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmregistroCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmregistroCasa dialog = new FrmregistroCasa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonregistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtancho;
    private javax.swing.JTextField txtbarrio;
    private javax.swing.JTextField txtlargo;
    private javax.swing.JTextField txtpisos;
    // End of variables declaration//GEN-END:variables
}
